name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo running tests 1
